shifa_products/cart/urls.py
from django.urls import path

from . import views

app_name = 'cart'

urlpatterns = [
    path(
        '',
        views.CartDetailView.as_view(),
        name='cart'
    ),
    path(
        'add_to_cart/<int:product_id>/',
        views.AddToCartCreateView.as_view(),
        name='add_to_cart'
    ),
    path(
        'item/<int:cart_item_id>/',
        views.CartItemUpdateView.as_view(),
        name='update_cart_item'
    ),
    path(
        'item/<int:cart_item_id>/delete',
        views.CartItemDeleteView.as_view(),
        name='delete_cart_item'
    ),
]

shifa_products/orders/urls.py
from django.urls import path

from . import views

app_name = 'orders'

urlpatterns = [
    path(
        '',
        views.OrderListView.as_view(),
        name='orders_list'
    ),
    path(
        'detail/<int:order_id>/',
        views.OrderDetailView.as_view(),
        name='order_detail'
    ),
    path(
        'detail/<int:order_id>/pdf',
        views.OrderPdfPrintView.as_view(),
        name='order_pdf'
    ),
    path(
        'checkout/',
        views.OrderCreateView.as_view(),
        name='checkout'
    ),
]

shifa_products/shifa_products/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path, reverse_lazy
from django.views.generic import CreateView

from .telegram_notifications import tawkto_webhook
from users.forms import UserForm

auth_urls = [
    path('', include('django.contrib.auth.urls')),
    path(
        'registration/',
        CreateView.as_view(
            template_name='registration/signup.html',
            form_class=UserForm,
            success_url=reverse_lazy('pages:index'),
        ),
        name='registration'
    )
]

urlpatterns = [
    path('', include('pages.urls', namespace='pages')),
    path('accounts/', include('allauth.urls')),
    path('admin/', admin.site.urls),
    path('auth/', include(auth_urls)),
    path('catalog/', include('catalog.urls', namespace='catalog')),
    path('users/', include('users.urls', namespace='users')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('order/', include('orders.urls', namespace='orders')),
    path('webhook/tawkto/', tawkto_webhook, name='tawkto_webhook'),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += static(
        settings.STATIC_URL, document_root=settings.STATIC_ROOT
    )
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )
    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)

shifa_products/users/urls.py
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path(
        'profile/<slug:username>',
        views.ProfileDetailView.as_view(),
        name='profile'
    ),
    path(
        'profile/<slug:username>/update/',
        views.ProfileUpdateView.as_view(),
        name='profile_update'
    ),
    path(
        'profile/create_address/',
        views.AddressUserCreateView.as_view(),
        name='address_create'
    ),
    path(
        'profile/delete_address/<int:address_id>/',
        views.AddressUserDeleteView.as_view(),
        name='address_delete'
    ),

]

shifa_products/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

from shifa_products.constants import MAX_LENTGH_ADDRESS_CONSTANTS


class CustomUser(AbstractUser):
    email = models.EmailField('correo electrónico', unique=True)
    first_name = models.CharField('nombre', max_length=150)
    last_name = models.CharField('apellido', max_length=150)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = [
        'username', 'first_name', 'last_name', 'password'
    ]


class AddressUser(models.Model):
    user = models.ForeignKey(
        CustomUser, on_delete=models.CASCADE, related_name='addresses'
    )
    location = models.ForeignKey(
        'catalog.Location', on_delete=models.CASCADE, related_name='addresses'
    )
    street = models.CharField(max_length=MAX_LENTGH_ADDRESS_CONSTANTS)
    postal_code = models.SmallIntegerField(null=True, blank=True)

    def __str__(self):
        return (
            f'{self.location}, {self.street}, {self.postal_code}'
        )

shifa_products/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

from .models import AddressUser, CustomUser


class UserForm(UserCreationForm):
    class Meta:
        model = CustomUser
        fields = ('username', 'email', 'first_name', 'last_name')


class UserUpdateForm(UserChangeForm):
    class Meta:
        model = CustomUser
        fields = ('username', 'email', 'first_name', 'last_name')


class AddressUserForm(forms.ModelForm):
    class Meta:
        model = AddressUser
        fields = ('location', 'street', 'postal_code')

shifa_products/users/views.py
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models.base import Model as Model
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views.generic import CreateView, DeleteView, DetailView, UpdateView

from .forms import AddressUserForm, UserUpdateForm
from .mixin import GetUserMixin, OnlyAuthorMixin
from .models import AddressUser
from shifa_products.constants import ADDRESS_AT_ORDERS_MESSAGE


User = get_user_model()


class ProfileDetailView(OnlyAuthorMixin, GetUserMixin, DetailView):
    """View for displaying the profile details of a user, including addresses.

    Inherits from:
        - OnlyAuthorMixin: Restricts access to the profile of the user.
        - GetUserMixin: Retrieves the user object based on the URL parameter.
        - DetailView: Displays the details of a single 'User' object.

    Methods:
        get_context_data(**kwargs):
            Adds the user's addresses to the context for rendering the profile
            view.
    """
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['address_user'] = self.get_object().addresses.all()
        return context


class ProfileUpdateView(OnlyAuthorMixin, GetUserMixin, UpdateView):
    """View for updating the user's profile information.

    Inherits from:
        - OnlyAuthorMixin: Restricts access to the profile of the user.
        - GetUserMixin: Retrieves the user object based on the URL parameter.
        - UpdateView: Displays and handles the update form for 'User' object.

    Attributes:
        form_class (Form): The form used to update the user's profile.

    Methods:
        get_success_url():
            Returns the URL to redirect to after successfully updating
            the profile.
    """
    form_class = UserUpdateForm

    def get_success_url(self):
        return reverse_lazy(
            'users:profile',
            kwargs={'username': self.get_object().username}
        )


class AddressUserCreateView(LoginRequiredMixin, CreateView):
    """View for creating a new address for the logged-in user.

    Inherits from:
        - LoginRequiredMixin: Ensures the user is authenticated.
        - CreateView: Handles the creation of a new 'AddressUser' object.

    Attributes:
        model (Model): The model associated with the view 'AddressUser'.
        form_class (Form): The form used to create a new address.
        template_name (str): The template used to render the address.

    Methods:
        form_valid(form):
            Assigns the current user to the address and saves the address.

        get_success_url():
            Returns the URL to redirect to after successfully creating the
            address.
    """
    model = AddressUser
    form_class = AddressUserForm
    template_name = 'users/user_address.html'

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy(
            'users:profile',
            kwargs={'username': self.request.user.username}
        )


class AddressUserDeleteView(OnlyAuthorMixin, DeleteView):
    """View for deleting an address associated with the logged-in user.

    Inherits from:
        - OnlyAuthorMixin: Restricts access to the owner of the address.
        - DeleteView: Handles the deletion of an 'AddressUser' object.

    Attributes:
        model (Model): The model associated with the view 'AddressUser'.
        pk_url_kwarg (str): The URL keyword used to identify the address.

    Methods:
        get(request, *args, **kwargs):
            Handles the address deletion, preventing deletion if the
            address is associated with any orders.

        get_success_url():
            Returns the URL to redirect to after successfully deleting
            the address.
    """
    model = AddressUser
    pk_url_kwarg = 'address_id'

    def get(self, request, *args, **kwargs):
        address = self.get_object()
        if address.orders.exists():
            messages.error(request, ADDRESS_AT_ORDERS_MESSAGE)
            return redirect('users:profile', username=address.user.username)
        return super().get(request, *args, **kwargs)

    def get_success_url(self):
        return reverse_lazy(
            'users:profile',
            kwargs={'username': self.request.user.username}
        )

shifa_products/templates/users/addressuser_confirm_delete.html
{% extends 'base.html' %}

{% block title %}Eliminar Dirección{% endblock %}

{% block content %}
<div class="container my-5">
    <h2 class="mb-4">Eliminar Dirección</h2>
    <p>¿Estás seguro de que deseas eliminar la siguiente dirección?</p>
    <div class="alert alert-warning">
        <strong>Dirección:</strong> {{ object }}<br>
    </div>
    <form method="post">
        {% csrf_token %}
        <div class="d-flex justify-content-end mt-3">
            <a href="{% url 'users:profile' object.user.username  %}" class="btn btn-secondary me-2">Cancelar</a>
            <button type="submit" class="btn btn-danger">Eliminar</button>
        </div>
    </form>
</div>
{% endblock %}

shifa_products/templates/users/customuser_detail.html
{% extends 'base.html' %}

{% block title %}Perfil: {{ object.username }}{% endblock %}

{% block content %}
<div class="container my-5">
  {% if messages %}
    <div class="container mt-3">
      {% for message in messages %}
        <div class="alert alert-info alert-dismissible fade show" role="alert">
          {{ message }}
        </div>
      {% endfor %}
    </div>
  {% endif %}
  <div class="row">
    <div class="col-lg-6 mb-4 d-flex">
      <div class="profile-card h-100 d-flex flex-column p-4 rounded shadow-sm border border-muted">
        <h4>Perfil de {{ object.username }}</h4>
        <p><strong>Nombre Completo:</strong> {{ object.get_full_name }}</p>
        <p><strong>Email:</strong> {{ object.email }}</p>
        <p><strong>Fecha de Registro:</strong> {{ object.date_joined }}</p>
        <p><strong>Último Inicio de Sesión:</strong> {{ object.last_login }}</p>
        <div class="mt-auto">
          <a href="{% url 'users:profile_update' object.username %}" class="btn btn-primary">Editar Perfil</a>
        </div>
      </div>
    </div>

    <div class="col-lg-6 mb-4 d-flex">
      <div class="profile-card h-100 d-flex flex-column p-4 rounded shadow-sm border border-muted">
        <p><strong>Direcciones asociadas para la entrega:</strong>
          {% if address_user %}
            {% for address in address_user %}
              <div class="address-item d-flex justify-content-between align-items-center">
                <p>{{ address.location }}, {{ address.street }}, {{ address.postal_code }}</p>
                <div class="text-end">
                  <a href="{% url 'users:address_delete' address.id %}" class="btn btn-sm btn-warning delete-btn">Eliminar</a>
                </div>
              </div>
            {% endfor %}
          {% else %}
            No se ha registrado una dirección.
          {% endif %}
        </p>
        <div class="mt-auto">
          <a href="{% url 'users:address_create' %}" class="btn btn-primary">Agregar Dirección de Entrega</a>
        </div>
      </div>
    </div>

    <div class="orders-section mt-4">
      <div class="profile-card p-4 rounded shadow-sm border border-muted">
        <h4>Mis órdenes</h4>
        <a href="{% url 'orders:orders_list' %}" class="btn btn-info">Ver mis órdenes</a>
      </div>
    </div>
  </div>
</div>
{% endblock %}

shifa_products/templates/users/customuser_form.html
{% extends 'base.html' %}

{% block title %}Actualizar Perfil{% endblock %}

{% block content %}
<div class="container my-5">
    <h2>Actualizar Perfil</h2>
    <form method="post">
        {% csrf_token %}
        {% if form.errors %}
            <div class="alert alert-danger">
                <strong>Por favor corrige los errores a continuación:</strong>
                <ul>
                    {% for field in form %}
                        {% for error in field.errors %}
                            <li>{{ field.label }}: {{ error }}</li>
                        {% endfor %}
                    {% endfor %}
                    {% for error in form.non_field_errors %}
                        <li>{{ error }}</li>
                    {% endfor %}
                </ul>
            </div>
        {% endif %}
        {% if messages %}
            <div class="alert alert-info">
                {% for message in messages %}
                    {{ message }}
                {% endfor %}
            </div>
        {% endif %}
        <div class="mb-3">
            <label for="{{ form.username.id_for_label }}" class="form-label">Nombre de Usuario</label>
            <input type="text" name="username" id="{{ form.username.id_for_label }}" class="form-control" value="{{ form.username.value }}" required>
        </div>
        
        <div class="mb-3">
            <label for="{{ form.first_name.id_for_label }}" class="form-label">Nombre</label>
            <input type="text" name="first_name" id="{{ form.first_name.id_for_label }}" class="form-control" value="{{ form.first_name.value }}" required>
        </div>
        
        <div class="mb-3">
            <label for="{{ form.last_name.id_for_label }}" class="form-label">Apellido</label>
            <input type="text" name="last_name" id="{{ form.last_name.id_for_label }}" class="form-control" value="{{ form.last_name.value }}" required>
        </div>
        
        <div class="mb-3">
            <label for="{{ form.email.id_for_label }}" class="form-label">Email</label>
            <input type="text" name="email" id="{{ form.email.id_for_label }}" class="form-control" value="{{ form.email.value }}" required>
        </div>
        <button type="submit" class="btn btn-primary">Actualizar</button>
        <a href="{% url 'users:profile' object.username %}" class="btn btn-secondary">Cancelar</a>
    </form>
</div>
{% endblock %}

shifa_products/templates/users/user_address.html
{% extends 'base.html' %}

{% block title %}
    Agregar Dirección
{% endblock %}

{% block content %}
<div class="container my-5">
    <div class="form-container">
        <h2 class="mb-4">Agregar Dirección</h2>

        <form method="post" class="mt-4">
            {% csrf_token %}
            <div class="mb-3">
                <label for="id_location" class="form-label">Ubicación</label>
                <select name="location" id="id_location" class="form-select" required>
                    {% for location in form.location.field.queryset %}
                        <option value="{{ location.id }}" {% if location.id == form.location.value %}selected{% endif %}>{{ location.name }}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="mb-3">
                <label for="id_street" class="form-label">Dirección</label>
                <input type="text" name="street" id="id_street" class="form-control" value="{{ form.street.value }}" required>
            </div>
            <div class="mb-3">
                <label for="id_postal_code" class="form-label">Código Postal</label>
                <input type="text" name="postal_code" id="id_postal_code" class="form-control" value="{{ form.postal_code.value }}">
            </div>
            <button type="submit" class="btn btn-primary">Agregar Dirección</button>
        </form>
        
        <a href="{% url 'users:profile' request.user.username %}" class="btn btn-secondary mt-3">Volver al Perfil</a>
    </div>
</div>
{% endblock %}