shifa_products/cart/urls.py
from django.urls import path

from . import views

app_name = 'cart'

urlpatterns = [
    path(
        '',
        views.CartDetailView.as_view(),
        name='cart'
    ),
    path(
        'add_to_cart/<int:product_id>/',
        views.AddToCartCreateView.as_view(),
        name='add_to_cart'
    ),
    path(
        'item/<int:cart_item_id>/',
        views.CartItemUpdateView.as_view(),
        name='update_cart_item'
    ),
    path(
        'item/<int:cart_item_id>/delete',
        views.CartItemDeleteView.as_view(),
        name='delete_cart_item'
    ),
]

shifa_products/catalog/urls.py
from django.urls import include, path

from . import views

app_name = 'catalog'

product_urls = [
    path(
        '<int:product_id>/',
        views.ProductDetailView.as_view(),
        name='product_detail'
    ),
    path(
        '<int:product_id>/review/',
        views.ReviewCreateView.as_view(),
        name='review_form'
    ),
    path(
        '<int:product_id>/review/<int:review_id>',
        views.ReviewUpdateView.as_view(),
        name='review_update'
    ),
    path(
        '<int:product_id>/delete_review/<int:review_id>',
        views.ReviewDeleteView.as_view(),
        name='review_delete'
    )
]

category_urls = [
    path(
        '',
        views.CategoryListView.as_view(),
        name='category_list'
    ),
    path(
        '<slug:category_slug>/',
        views.ProductListView.as_view(),
        name='category_product_list'
    )
]

urlpatterns = [
    path(
        'category/', include(category_urls)
    ),
    path(
        'product/', include(product_urls)
    ),
    path(
        'search/',
        views.ProductSearchView.as_view(),
        name='product_search'
    ),
]

shifa_products/orders/urls.py
from django.urls import path

from . import views

app_name = 'orders'

urlpatterns = [
    path(
        '',
        views.OrderListView.as_view(),
        name='orders_list'
    ),
    path(
        'detail/<int:order_id>/',
        views.OrderDetailView.as_view(),
        name='order_detail'
    ),
    path(
        'detail/<int:order_id>/pdf',
        views.OrderPdfPrintView.as_view(),
        name='order_pdf'
    ),
    path(
        'checkout/',
        views.OrderCreateView.as_view(),
        name='checkout'
    ),
]

shifa_products/shifa_products/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path, reverse_lazy
from django.views.generic import CreateView

from .telegram_notifications import tawkto_webhook
from users.forms import UserForm

auth_urls = [
    path('', include('django.contrib.auth.urls')),
    path(
        'registration/',
        CreateView.as_view(
            template_name='registration/signup.html',
            form_class=UserForm,
            success_url=reverse_lazy('pages:index'),
        ),
        name='registration'
    )
]

urlpatterns = [
    path('', include('pages.urls', namespace='pages')),
    path('accounts/', include('allauth.urls')),
    path('admin/', admin.site.urls),
    path('auth/', include(auth_urls)),
    path('catalog/', include('catalog.urls', namespace='catalog')),
    path('users/', include('users.urls', namespace='users')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('order/', include('orders.urls', namespace='orders')),
    path('webhook/tawkto/', tawkto_webhook, name='tawkto_webhook'),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += static(
        settings.STATIC_URL, document_root=settings.STATIC_ROOT
    )
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )
    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)

shifa_products/cart/models.py
from django.contrib.auth import get_user_model
from django.db import models

from catalog.models import Product


User = get_user_model()


class Cart(models.Model):
    user = models.ForeignKey(
        User,
        related_name='cart',
        on_delete=models.CASCADE,
        verbose_name='Usuario'
    )
    created_at = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Fecha de creación'
    )

    class Meta:
        verbose_name = 'Carrito de compra'
        verbose_name_plural = 'Carritos de compra'
        ordering = ['-created_at']

    def __str__(self):
        return f'Carrito de {self.user.username} creado: {self.created_at.date()}'


class CartItem(models.Model):
    cart = models.ForeignKey(
        Cart,
        related_name='cart_items',
        on_delete=models.CASCADE,
        verbose_name='Carrito de compra'
    )
    product = models.ForeignKey(
        Product,
        related_name='cart_items',
        on_delete=models.CASCADE,
        verbose_name='Producto'
    )
    quantity = models.PositiveSmallIntegerField(
        default=1, verbose_name='Cantidad'
    )

    class Meta:
        verbose_name = 'Artículo en carrito'
        verbose_name_plural = 'Artículos en carrito'
        ordering = ['quantity', 'product__price']

    def __str__(self):
        return (
            f'Producto {self.product} en carrito de {self.cart.user.username}'
        )

shifa_products/cart/forms.py
from django import forms

from .models import Cart, CartItem


class CartItemForm(forms.ModelForm):
    class Meta:
        model = CartItem
        fields = ('quantity',)


class CartForm(forms.ModelForm):
    class Meta:
        model = Cart
        fields = '__all__'

shifa_products/cart/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import F, Sum
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy
from django.views.generic import CreateView, DeleteView, DetailView, UpdateView

from .forms import CartItemForm
from .mixins import (
    CartItemMixin, CartItemUpdateDeleteSuccessUrl, OnlyAuthorCartMixin
)
from .models import Cart, CartItem
from catalog.models import Product
from shifa_products.constants import (
    SUCCESFUL_ADD_T0_CART_MESSAGE, SIGN_IN_TO_ADD_CART_MESSAGE
)


class AddToCartCreateView(LoginRequiredMixin, CreateView):
    """View for adding a product to the cart.

    Inherits:
        - LoginRequiredMixin: Ensures the user is authenticated.
        - CreateView: Handles the creation of a new `CartItem`.

    Attributes:
        model (Model): The model for the view 'CartItem'.
        form_class (Form): The form for creating 'CartItem'.
        pk_url_kwarg (str): The URL keyword for the product 'product_id'.
        product (Product): The product to be added to the cart.
        cart (Cart): The cart for the logged-in user.

    Methods:
        dispatch(request, *args, **kwargs):
            Handles authentication and initializes the cart/product.
        form_valid(form):
            Assigns the product and cart to the `CartItem`.
        get_success_url():
            Returns the URL for redirection after success.
    """
    model = CartItem
    form_class = CartItemForm
    pk_url_kwarg = 'product_id'
    product = None
    cart = None

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            messages.error(request, SIGN_IN_TO_ADD_CART_MESSAGE)
            return redirect('login')
        self.product = get_object_or_404(
            Product,
            pk=self.kwargs.get(self.pk_url_kwarg)
        )
        self.cart, created = Cart.objects.get_or_create(
            user=self.request.user
        )
        return super().dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        form.instance.product = self.product
        form.instance.cart = self.cart
        messages.success(self.request, SUCCESFUL_ADD_T0_CART_MESSAGE)
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy(
            'catalog:category_product_list',
            kwargs={'category_slug': self.object.product.category.slug}
        )


class CartDetailView(OnlyAuthorCartMixin, DetailView):
    """View for displaying the details of the user's cart.

    Inherits from:
        - OnlyAuthorCartMixin: Restricts access to the cart owner.
        - DetailView: Displays the details of a single cart.

    Methods:
        get_object(queryset=None):
            Fetches or creates the cart for the logged-in user.

        get_context_data(**kwargs):
            Adds additional context to the template, such as cart items,
            total cost, and user addresses.
    """
    def get_object(self, queryset=None):
        cart, created = Cart.objects.get_or_create(
            user=self.request.user
        )
        return cart

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        cart_items = self.get_object().cart_items.select_related(
            'product'
        ).annotate(total_item=F('quantity') * F('product__price'))
        context['cart_item'] = cart_items
        context['cart_total'] = cart_items.aggregate(
            cart_total=Sum(F('quantity') * F('product__price'), default=0)
        )['cart_total']
        context['addresses'] = self.request.user.addresses.all()
        return context


class CartItemUpdateView(
    CartItemMixin, CartItemUpdateDeleteSuccessUrl, UpdateView
):
    """View for updating a cart item.

    Inherits:
        - CartItemMixin: Handles cart item-specific logic.
        - CartItemUpdateDeleteSuccessUrl: Provides the URL after update.
        - UpdateView: Handles the update of a `CartItem`.

    Attributes:
        form_class (Form): The form for updating `CartItem`.
    """
    form_class = CartItemForm


class CartItemDeleteView(
    CartItemMixin, CartItemUpdateDeleteSuccessUrl, DeleteView
):
    """View for deleting a cart item.

    Inherits:
        - CartItemMixin: Handles cart item-specific logic.
        - CartItemUpdateDeleteSuccessUrl: Provides the URL after deletion.
        - DeleteView: Handles the deletion of a `CartItem`.
    """
    pass

shifa_products/templates/cart/cart_detail.html
{% extends 'base.html' %}

{% block title %}Carrito{% endblock %}

{% block content %}
<div class="container my-5">
  <h2 class="mb-4">Tu Carrito</h2>
  {% if cart_item %}
    <div class="table-responsive">
      <table class="table table-striped">
        <thead>
          <tr>
            <th>Producto</th>
            <th>Cantidad</th>
            <th>Precio (USD)</th>
            <th>Total (USD)</th>
            <th>Acciones</th>
          </tr>
        </thead>
        <tbody>
          {% for item in cart_item %}
          <tr>
            <td>{{ item.product.name }}</td>
            <td>{{ item.quantity }}</td>
            <td>{{ item.product.price }}</td>
            <td>{{ item.total_item|floatformat:2 }}</td>
            <td>
              <a href="{% url 'cart:update_cart_item' item.id %}" class="btn btn-sm btn-warning py-1 mt-1 mb-1 delete-btn">Editar</a>
              <a href="{% url 'cart:delete_cart_item' item.id %}" class="btn btn-sm btn-warning py-1 mt-1 mb-1 delete-btn">Eliminar</a>
            </td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
    <div class="d-flex justify-content-end align-items-center mt-4">
      <h4>Total: {{ cart_total|floatformat:2 }} USD</h4>
    </div>
    <div class="mt-4">
      <h4>Selecciona una dirección para el envío:</h4>
      <form action="{% url 'orders:checkout' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
          <label for="address">Dirección de envío</label>
          <select id="address" name="address" class="form-control">
            {% for address in addresses %}
              <option value="{{ address.id }}">
                {{ address }}
              </option>
            {% endfor %}
          </select>
        </div>
        <button type="submit" class="btn btn-primary mt-3">Proceder al Pago</button>
      </form>
    </div>
    <div class="mt-3">
      <a href="{% url 'catalog:category_list' %}" class="btn btn-secondary">Seguir Comprando</a>
    </div>
  {% else %}
      <p>No hay productos en tu carrito.</p>
      <a href="{% url 'catalog:category_list' %}" class="btn btn-primary">Explorar Productos</a>
  {% endif %}
</div>
{% endblock %}

shifa_products/templates/cart/cartitem_confirm_delete.html
{% extends 'base.html' %}

{% block title %}Eliminar Producto del Carrito{% endblock %}

{% block content %}
<div class="container my-5">
    <h2 class="mb-4">Eliminar Producto del Carrito</h2>
    <p>¿Estás seguro de que deseas eliminar el siguiente producto de tu carrito?</p>
    <div class="alert alert-warning">
        <strong>Producto:</strong> {{ object.product.name }}<br>
        <strong>Cantidad:</strong> {{ object.quantity }}<br>
        <strong>Precio:</strong> {{ object.product.price|floatformat:2 }} USD
    </div>
    <form method="post">
        {% csrf_token %}
        <div class="d-flex justify-content-end mt-3">
            <a href="{% url 'cart:cart' %}" class="btn btn-secondary me-2">Cancelar</a>
            <button type="submit" class="btn btn-danger">Eliminar</button>
        </div>
    </form>
</div>
{% endblock %}

shifa_products/templates/cart/cartitem_form.html
{% extends 'base.html' %}

{% block title %}Editar Ítem del Carrito{% endblock %}

{% block content %}
<div class="container my-5">
  <h2 class="mb-4">Editar Ítem del Carrito</h2>
  
  <form method="post">
    {% csrf_token %}
    
    <div class="mb-3">
      <label for="product_name" class="form-label">Producto</label>
      <input type="text" id="product_name" class="form-control" value="{{ object.product.name }}" disabled>
    </div>

    <div class="mb-3">
      <label for="quantity" class="form-label">Cantidad</label>
      <input type="number" id="quantity" name="quantity" class="form-control" min="1" value="{{ object.quantity }}">
    </div>

    <div class="mb-3">
      <label for="price" class="form-label">Precio Unitario (USD)</label>
      <input type="text" id="price" class="form-control" value="{{ object.product.price }}" disabled>
    </div>

    <div class="d-flex justify-content-end">
      <button type="submit" class="btn btn-success">
        <i class="bi bi-floppy-fill"></i> Actualizar
      </button>
      <a href="{% url 'cart:cart' %}" class="btn btn-secondary ms-2">
        <i class="bi bi-arrow-left-circle"></i> Regresar al carrito
      </a>
    </div>
  </form>
</div>
{% endblock %}