shifa_products/cart/urls.py
from django.urls import path

from . import views

app_name = 'cart'

urlpatterns = [
    path(
        '',
        views.CartDetailView.as_view(),
        name='cart'
    ),
    path(
        'add_to_cart/<int:product_id>/',
        views.AddToCartCreateView.as_view(),
        name='add_to_cart'
    ),
    path(
        'item/<int:cart_item_id>/',
        views.CartItemUpdateView.as_view(),
        name='update_cart_item'
    ),
    path(
        'item/<int:cart_item_id>/delete',
        views.CartItemDeleteView.as_view(),
        name='delete_cart_item'
    ),
]

shifa_products/catalog/urls.py
from django.urls import include, path

from . import views

app_name = 'catalog'

product_urls = [
    path(
        '<int:product_id>/',
        views.ProductDetailView.as_view(),
        name='product_detail'
    ),
    path(
        '<int:product_id>/review/',
        views.ReviewCreateView.as_view(),
        name='review_form'
    ),
    path(
        '<int:product_id>/review/<int:review_id>',
        views.ReviewUpdateView.as_view(),
        name='review_update'
    ),
    path(
        '<int:product_id>/delete_review/<int:review_id>',
        views.ReviewDeleteView.as_view(),
        name='review_delete'
    )
]

category_urls = [
    path(
        '',
        views.CategoryListView.as_view(),
        name='category_list'
    ),
    path(
        '<slug:category_slug>/',
        views.ProductListView.as_view(),
        name='category_product_list'
    )
]

urlpatterns = [
    path(
        'category/', include(category_urls)
    ),
    path(
        'product/', include(product_urls)
    ),
    path(
        'search/',
        views.ProductSearchView.as_view(),
        name='product_search'
    ),
]

shifa_products/shifa_products/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path, reverse_lazy
from django.views.generic import CreateView

from .telegram_notifications import tawkto_webhook
from users.forms import UserForm

auth_urls = [
    path('', include('django.contrib.auth.urls')),
    path(
        'registration/',
        CreateView.as_view(
            template_name='registration/signup.html',
            form_class=UserForm,
            success_url=reverse_lazy('pages:index'),
        ),
        name='registration'
    )
]

urlpatterns = [
    path('', include('pages.urls', namespace='pages')),
    path('accounts/', include('allauth.urls')),
    path('admin/', admin.site.urls),
    path('auth/', include(auth_urls)),
    path('catalog/', include('catalog.urls', namespace='catalog')),
    path('users/', include('users.urls', namespace='users')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('order/', include('orders.urls', namespace='orders')),
    path('webhook/tawkto/', tawkto_webhook, name='tawkto_webhook'),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += static(
        settings.STATIC_URL, document_root=settings.STATIC_ROOT
    )
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )
    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)

shifa_products/catalog/models.py
from django.contrib.auth import get_user_model
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models

from .utils import optimize_image
from .validators import validate_image
from shifa_products.constants import (
    HELP_TEXT_SLUG, MAX_LENGTH_NAME, MAX_LENGTH_REVIEW, MAX_LENGTH_TITLE
)


User = get_user_model()


class BaseModel(models.Model):
    name = models.CharField(
        max_length=MAX_LENGTH_NAME,
        verbose_name='Nombre'
    )

    class Meta:
        abstract = True


class Category(BaseModel):
    slug = models.SlugField(
        unique=True,
        help_text=(HELP_TEXT_SLUG)
    )

    class Meta:
        verbose_name = 'Categoría'
        verbose_name_plural = 'Categorías'
        ordering = ['name']

    def __str__(self):
        return self.name


class Location(BaseModel):
    pass

    class Meta:
        verbose_name = 'Localidad'
        verbose_name_plural = 'Localidades'
        ordering = ['id']

    def __str__(self):
        return self.name


class Product(BaseModel):
    description = models.TextField(
        verbose_name='Descripción'
    )
    image = models.ImageField(
        upload_to='products/images/',
        verbose_name='imagen',
        validators=(validate_image,)
    )
    is_available = models.BooleanField(
        default=True,
        verbose_name='Disponible'
    )
    price = models.DecimalField(
        max_digits=5,
        decimal_places=2,
        verbose_name='Precio'
    )
    category = models.ForeignKey(
        Category,
        related_name='products',
        on_delete=models.SET_NULL,
        null=True,
        verbose_name='Categoría'
    )
    location = models.ManyToManyField(
        Location,
        related_name='products',
        verbose_name='Localidad'
    )

    class Meta:
        verbose_name = 'Producto'
        verbose_name_plural = 'Productos'
        ordering = ['id']

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        optimize_image(self.image)

    def __str__(self):
        return self.name


class Review(models.Model):
    title = models.CharField(
        max_length=MAX_LENGTH_TITLE,
        verbose_name='Título'
    )
    review = models.CharField(
        max_length=MAX_LENGTH_REVIEW,
        verbose_name='Reseña'
    )
    date = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Fecha de creación'
    )
    taste_stars = models.IntegerField(
        default=5,
        validators=[MinValueValidator(1), MaxValueValidator(5)],
        verbose_name='Sabor'
    )
    quality_stars = models.IntegerField(
        default=5,
        validators=[MinValueValidator(1), MaxValueValidator(5)],
        verbose_name='Calidad'
    )
    product = models.ForeignKey(
        Product,
        related_name='reviews',
        on_delete=models.CASCADE,
        verbose_name='Producto'
    )
    user = models.ForeignKey(
        User,
        related_name='reviews',
        on_delete=models.CASCADE,
        verbose_name='usuario'
    )
    location = models.ForeignKey(
        Location,
        on_delete=models.SET_NULL,
        null=True,
        verbose_name='localidad'
    )

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=['product', 'user'],
                name='unique_name_owner'
            )
        ]
        ordering = ['-date']
        verbose_name = 'Reseña'
        verbose_name_plural = 'Reseñas'

    def __str__(self):
        return self.title

shifa_products/catalog/forms.py
from django import forms

from .models import Review
from .validators import validate_stars


class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = (
            'title', 'review', 'taste_stars', 'quality_stars', 'location'
        )

    def clean_taste_stars(self):
        taste_stars = self.cleaned_data.get('taste_stars')
        return validate_stars(taste_stars)

    def clean_quality_stars(self):
        quality_stars = self.cleaned_data.get('quality_stars')
        return validate_stars(quality_stars)

shifa_products/catalog/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.paginator import Paginator
from django.db.models import Avg, Count, Q
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy
from django.views.generic import (
    CreateView,
    DetailView,
    ListView,
    UpdateView,
    DeleteView
)

from .forms import ReviewForm
from .mixins import OnlyAuthorMixin
from .models import Category, Product, Review
from cart.forms import CartItemForm
from shifa_products.constants import (
    MAX_REVIEWS_MESSAGE, SIGN_IN_TO_ADD_REVIEW_MESSAGE
)


class CategoryListView(ListView):
    """View for listing all product categories.

    Inherits from:
        - ListView: Displays a list of 'Category' objects.

    Attributes:
        model (Model): The model associated with the view 'Category'.
        context_object_name (str): Name of the context variable.

    Methods:
        get_queryset():
            Returns all 'Category' objects.
    """
    model = Category
    context_object_name = 'categories'


class ProductListView(ListView):
    """View for listing products in a specific category.

    Inherits from:
        - ListView: Displays a list of 'Product' objects.

    Attributes:
        model (Model): The model associated with the view 'Product'.
        paginate_by (int): Number of products per page.
        context_object_name (str): Name of the context variable.

    Methods:
        get_category():
            Retrieves the category associated with the URL
            parameter 'category_slug'.

        get_queryset():
            Returns all products for the specific category.

        get_context_data(**kwargs):
            Adds additional context, such as the current category
            and a 'CartItemForm' instance.
    """
    model = Product
    paginate_by = 10
    context_object_name = 'products'

    def get_category(self):
        return get_object_or_404(
            Category, slug=self.kwargs.get('category_slug')
        )

    def get_queryset(self):
        return Product.objects.filter(
            category=self.get_category()
        ).select_related('category')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['category'] = self.get_category()
        context['form'] = CartItemForm()
        return context


class ProductSearchView(ListView):
    """View for searching products based on a query.

    Inherits from:
        - ListView: Displays a list of 'Product' objects.

    Attributes:
        model (Model): The model associated with the view 'Product`.
        context_object_name (str): Name of the context variable.

    Methods:
        get_query():
            Retrieves the search query from the GET request.

        get_queryset():
            Filters the products based on the search query.

        get_context_data(**kwargs):
            Adds additional context, such as the search query
            and an active search flag.
    """
    model = Product
    context_object_name = 'products'

    def get_query(self):
        return self.request.GET.get('q')

    def get_queryset(self):
        query = self.get_query()
        object_list = Product.objects.filter((
            Q(name__icontains=query)
            | Q(description__icontains=query)
            | Q(category__name__icontains=query)
            | Q(category__slug__icontains=query)
            ) & Q(is_available=True)
        )
        return object_list

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['search_active'] = True
        context['query'] = self.get_query()
        return context


class ProductDetailView(DetailView):
    """View for displaying the details of a specific product.

    Inherits from:
        - DetailView: Displays a single `Product` object.

    Attributes:
        model (Model): The model associated with the view 'Product'.
        pk_url_kwarg (str): The URL keyword used to identify the product.

    Methods:
        get_queryset():
            Annotates products with average review ratings and review count.

        get_context_data(**kwargs):
            Adds product details, paginated reviews, and a 'CartItemForm'
            to the context.
    """
    model = Product
    pk_url_kwarg = 'product_id'

    def get_queryset(self):
        return Product.objects.annotate(
            avg_quality_stars=Avg('reviews__quality_stars'),
            avg_taste_stars=Avg('reviews__taste_stars'),
            review_count=Count('reviews')
        ).select_related('category')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        paginator = Paginator(self.get_object().reviews.all(), 3)
        page = self.request.GET.get('page')
        context['reviews'] = paginator.get_page(page)
        context['form'] = CartItemForm()
        return context


class ReviewCreateView(LoginRequiredMixin, CreateView):
    """View for creating a review for a specific product.

    Inherits from:
        - LoginRequiredMixin: Ensures the user is authenticated.
        - CreateView: Handles the creation of a new 'Review' object.

    Attributes:
        model (Model): The model associated with the view 'Review'.
        form_class (Form): The form class used to create `Review`.
        pk_url_kwarg (str): The URL keyword used to identify the product.

    Methods:
        handle_no_permission():
            Handles the case when the user is not authenticated and shows
            a message.

        get_object():
            Retrieves the 'Product' object based on the 'product_id' from
            the URL.

        get():
            Verifies if the user has already submitted a review for the
            product, otherwise proceeds.

        get_context_data(**kwargs):
            Adds the 'Product' object to the context.

        form_valid(form):
            Sets the 'user' and 'product' fields on the 'Review' instance
            before saving.

        get_success_url():
            Returns the URL to redirect to after successfully creating
            the review.
    """
    model = Review
    form_class = ReviewForm
    pk_url_kwarg = 'product_id'

    def handle_no_permission(self):
        messages.error(self.request, SIGN_IN_TO_ADD_REVIEW_MESSAGE)
        return super().handle_no_permission()

    def get_object(self, queryset=None):
        return get_object_or_404(
            Product,
            pk=self.kwargs.get(self.pk_url_kwarg)
        )

    def get(self, request, *args, **kwargs):
        product = self.get_object()
        if Review.objects.filter(user=request.user, product=product):
            messages.error(
                request,
                MAX_REVIEWS_MESSAGE
            )
            return redirect('catalog:product_detail', product_id=product.pk)
        return super().get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['product'] = self.get_object()
        return context

    def form_valid(self, form):
        form.instance.user = self.request.user
        form.instance.product = self.get_object()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy(
            'catalog:product_detail',
            kwargs={'product_id': self.get_object().pk}
        )


class ReviewUpdateView(OnlyAuthorMixin, UpdateView):
    """View for updating a review.

    Inherits from:
        - OnlyAuthorMixin: Restricts access to the review owner.
        - UpdateView: Handles updating an existing 'Review' object.

    Attributes:
        model (Model): The model associated with the view 'Review'.
        pk_url_kwarg (str): The URL keyword used to identify the review.
        form_class (Form): The form class used to update 'Review'..

    Methods:
        get_context_data(**kwargs):
            Adds the 'Product' object associated with the review to
            the context.

        get_success_url():
            Returns the URL to redirect to after successfully updating
            the review.
    """
    model = Review
    pk_url_kwarg = 'review_id'
    form_class = ReviewForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['product'] = self.object.product
        return context

    def get_success_url(self):
        return reverse_lazy(
            'catalog:product_detail',
            kwargs={'product_id': self.object.product.pk}
        )


class ReviewDeleteView(OnlyAuthorMixin, DeleteView):
    """View for deleting a review.

    Inherits from:
        - OnlyAuthorMixin: Restricts access to the review owner.
        - DeleteView: Handles the deletion of an existing 'Review' object.

    Attributes:
        model (Model): The model associated with the view 'Review'.
        pk_url_kwarg (str): The URL keyword argument used to identify the
        review.

    Methods:
        get_success_url():
            Returns the URL to redirect to after successfully deleting the
            review.
    """
    model = Review
    pk_url_kwarg = 'review_id'

    def get_success_url(self):
        return reverse_lazy(
            'catalog:product_detail',
            kwargs={'product_id': self.object.product.pk}
        )

shifa_products/templates/catalog/product_detail.html
{% extends 'base.html' %}

{% block title %}{{ product.name }}{% endblock %}

{% block content %}
<div class="container my-5">
  <div class="row">
    <figure class="col-md-6">
      <img src="{{ product.image.url }}" class="img-fluid" alt="{{ product.name }}">
    </figure>
    <div class="col-md-6">
      <h2>{{ product.name }}</h2>
      <p class="text-primary">{{ product.price }} USD</p>
      <p><strong>Categoría:</strong> 
        <a href="{% url 'catalog:category_product_list' category_slug=product.category.slug %}" class="btn btn-light">
          {{ product.category }}
        </a>
      </p>
      <p>{{ product.description }}</p>
      <p>
        <strong>Calidad : </strong>
        {% for i in "12345" %}
          {% if forloop.counter <= product.avg_quality_stars %}
            <i class="bi bi-star-fill text-warning"></i>
          {% else %}
            <i class="bi bi-star text-warning"></i>
          {% endif %}
        {% endfor %}
      </p>
      <p>
        <strong>Sabor : </strong>
        {% for i in "12345" %}
          {% if forloop.counter <= product.avg_taste_stars %}
            <i class="bi bi-star-fill text-warning"></i>
          {% else %}
            <i class="bi bi-star text-warning"></i>
          {% endif %}
        {% endfor %}
      </p>
      <form action="{% url 'cart:add_to_cart' product.id %}" method="post" class="d-inline">
        {% csrf_token %}
        <input type="hidden" name="quantity" value="1">
        <button class="btn btn-success" type="submit">
          <i class="bi bi-cart"></i> Agregar a carrito
        </button>
      </form>
      <div class="mt-4">
        <h5>Compartir este producto:</h5>
        <div class="share-buttons-container">
          <label for="product-url" class="form-label"></label>
          <div class="input-group">
            <div>
              <button class="copy-button me-2" onclick="navigator.clipboard.writeText('{{ request.build_absolute_uri }}')">
                <span
                  data-text-end="URL copiada!"
                  data-text-initial="Copiar URL"
                  class="tooltip"
                ></span>
                <span>
                  <svg
                    class="clipboard"
                    xmlns="http://www.w3.org/2000/svg"
                    version="1.1"
                    xmlns:xlink="http://www.w3.org/1999/xlink"
                    width="20"
                    height="20"
                    x="0"
                    y="0"
                    viewBox="0 0 6.35 6.35"
                    style="enable-background:new 0 0 512 512"
                    xml:space="preserve"
                  >
                    <g>
                      <path
                        d="M2.43.265c-.3 0-.548.236-.573.53h-.328a.74.74 0 0 0-.735.734v3.822a.74.74 0 0 0 .735.734H4.82a.74.74 0 0 0 .735-.734V1.529a.74.74 0 0 0-.735-.735h-.328a.58.58 0 0 0-.573-.53zm0 .529h1.49c.032 0 .049.017.049.049v.431c0 .032-.017.049-.049.049H2.43c-.032 0-.05-.017-.05-.049V.843c0-.032.018-.05.05-.05zm-.901.53h.328c.026.292.274.528.573.528h1.49a.58.58 0 0 0 .573-.529h.328a.2.2 0 0 1 .206.206v3.822a.2.2 0 0 1-.206.205H1.53a.2.2 0 0 1-.206-.205V1.529a.2.2 0 0 1 .206-.206z"
                        fill="currentColor"
                      ></path>
                    </g>
                  </svg>
                  <svg
                    class="checkmark"
                    xmlns="http://www.w3.org/2000/svg"
                    version="1.1"
                    xmlns:xlink="http://www.w3.org/1999/xlink"
                    width="18"
                    height="18"
                    x="0"
                    y="0"
                    viewBox="0 0 24 24"
                    style="enable-background:new 0 0 512 512"
                    xml:space="preserve"
                  >
                    <g>
                      <path
                        d="M9.707 19.121a.997.997 0 0 1-1.414 0l-5.646-5.647a1.5 1.5 0 0 1 0-2.121l.707-.707a1.5 1.5 0 0 1 2.121 0L9 14.171l9.525-9.525a1.5 1.5 0 0 1 2.121 0l.707.707a1.5 1.5 0 0 1 0 2.121z"
                        fill="currentColor"
                        data-original="#000000"
                      ></path>
                    </g>
                  </svg>
                </span>
              </button>
            </div>
            <div>
              <a href="https://api.whatsapp.com/send?text=Mira este producto: {{ product.name }}: {{ request.build_absolute_uri }}" target="_blank" class="whatsapp-button me-2">
                <div class="whatsapp-sign">
                  <svg viewBox="0 0 16 16">
                    <path d="M13.601 2.326A7.854 7.854 0 0 0 7.994 0C3.627 0 .068 3.558.064 7.926c0 1.399.366 2.76 1.057 3.965L0 16l4.204-1.102a7.933 7.933 0 0 0 3.79.965h.004c4.368 0 7.926-3.558 7.93-7.93A7.898 7.898 0 0 0 13.6 2.326zM7.994 14.521a6.573 6.573 0 0 1-3.356-.92l-.24-.144-2.494.654.666-2.433-.156-.251a6.56 6.56 0 0 1-1.007-3.505c0-3.626 2.957-6.584 6.591-6.584a6.56 6.56 0 0 1 4.66 1.931 6.557 6.557 0 0 1 1.928 4.66c-.004 3.639-2.961 6.592-6.592 6.592zm3.615-4.934c-.197-.099-1.17-.578-1.353-.646-.182-.065-.315-.099-.445.099-.133.197-.513.646-.627.775-.114.133-.232.148-.43.05-.197-.1-.836-.308-1.592-.985-.59-.525-.985-1.175-1.103-1.372-.114-.198-.011-.304.088-.403.087-.088.197-.232.296-.346.1-.114.133-.198.198-.33.065-.134.034-.248-.015-.347-.05-.099-.445-1.076-.612-1.47-.16-.389-.323-.335-.445-.34-.114-.007-.247-.007-.38-.007a.729.729 0 0 0-.529.247c-.182.198-.691.677-.691 1.654 0 .977.71 1.916.81 2.049.098.133 1.394 2.132 3.383 2.992.47.205.84.326 1.129.418.475.152.904.129 1.246.08.38-.058 1.171-.48 1.338-.943.164-.464.164-.86.114-.943-.049-.084-.182-.133-.38-.232z"></path>
                  </svg>
                </div>
                <div class="whatsapp-text">Whatsapp</div>
              </a>
            </div>
          </div>
        </div>
      </div>      
    </div>
  </div>
  {% if messages %}
    <div class="container mt-3">
      {% for message in messages %}
        <div class="alert alert-info alert-dismissible fade show" role="alert">
          {{ message }}
        </div>
      {% endfor %}
    </div>
  {% endif %}
  <div class="container mt-5">
    <h4 class="mb-4">Reseñas ({{ product.review_count }}) </h4>
    <a href="{% url 'catalog:review_form' product.id %}" class="btn btn-primary mb-4">Dejar una reseña</a>
    <ul class="list-unstyled">
      {% for review in reviews %}
      <li class="review-card mb-4 p-3 border rounded">
        <div class="d-flex align-items-start">
          <span class="me-3 rounded-circle" style="width: 50px;">
            {{ review.user.username }}
          </span>
          <div class="review-content">
            <h5 class="mt-0 mb-1"><small class="text-muted">{{ review.date }}</small></h5>
            <p class="fw-bold mb-1">{{ review.title }}</p>
            <p class="mb-1"><strong>Reseña:</strong> {{ review.review }}</p>
            <p class="mb-1">
              <strong>Sabor:</strong> 
              {% for i in "12345" %}
                {% if forloop.counter <= review.taste_stars %}
                  <i class="bi bi-star-fill text-warning"></i>
                {% else %}
                  <i class="bi bi-star text-warning"></i>
                {% endif %}
              {% endfor %}
            </p>
            <p class="mb-1">
              <strong>Calidad:</strong> 
              {% for i in "12345" %}
                {% if forloop.counter <= review.quality_stars %}
                  <i class="bi bi-star-fill text-warning"></i>
                {% else %}
                  <i class="bi bi-star text-warning"></i>
                {% endif %}
              {% endfor %}
            </p>
            <p class="mb-0"><strong>Localidad:</strong> {{ review.location }}</p>
            {% if request.user == review.user %}
              <div class="mt-3">
                <a href="{% url 'catalog:review_update' product.id review.id %}" class="btn btn-warning btn-sm">Editar</a>
                <a href="{% url 'catalog:review_delete' product.id review.id %}" class="btn btn-warning btn-sm">Eliminar</a>
              </div>
            {% endif %}
          </div>
        </div>
      </li>
      {% endfor %}
    </ul>
    <div class="text-center mt-4">
      <div class="d-flex justify-content-between">
        {% if reviews %}
          {% if reviews.has_previous %}
            <a href="?page={{ reviews.previous_page_number }}" class="btn btn-secondary">← Atrás</a>
          {% endif %}

          {% if reviews.has_next %}
            <a href="?page={{ reviews.next_page_number }}" class="btn btn-secondary">Adelante →</a>
          {% endif %}
        {% endif %}
      </div>
    </div>
  </div>
</div>
{% endblock %}

shifa_products/templates/catalog/review_confirm_delete.html
{% extends 'base.html' %}

{% block title %}Confirmar Eliminación{% endblock %}

{% block content %}
<div class="container my-5">
  <h2>¿Estás seguro de que quieres eliminar esta reseña para {{ review.product.name }}?</h2>
  <p>
    Esta acción no se puede deshacer. La reseña será eliminada permanentemente.
  </p>

  <form method="post">
    {% csrf_token %}
    <button type="submit" class="btn btn-danger">Eliminar</button>
    <a href="{% url 'catalog:product_detail' review.product.id %}" class="btn btn-secondary">Cancelar</a>
  </form>
</div>
{% endblock %}

shifa_products/templates/catalog/review_form.html
{% extends 'base.html' %}

{% block title %}Dejar una Reseña{% endblock %}

{% block content %}
<div class="container my-5">
  <h2>Dejar una Reseña para {{ product.name }}</h2>

  <form method="post">
    {% csrf_token %}
    <div class="mb-3">
      <label for="id_title" class="form-label">Título</label>
      <input type="text" name="title" maxlength="100" class="form-control" id="id_title" value="{{ form.title.value|default:'' }}">
      {% if form.title.errors %}
        <div class="text-danger">
          {{ form.title.errors }}
        </div>
      {% endif %}
    </div>
    <div class="mb-3">
      <label for="id_review" class="form-label">Reseña</label>
      <textarea name="review" maxlength="1000" class="form-control" id="id_review">{{ form.review.value|default:''}}</textarea>
      {% if form.review.errors %}
        <div class="text-danger">
          {{ form.review.errors }}
        </div>
      {% endif %}
    </div>
    <div class="mb-3">
      <label for="id_taste_stars" class="form-label">Estrellas de Sabor</label>
      <input type="number" name="taste_stars" value="{{ form.taste_stars.value|default:"5" }}" class="form-control" id="id_taste_stars" min="1" max="5">
      {% if form.taste_stars.errors %}
        <div class="text-danger">
          {{ form.taste_stars.errors }}
        </div>
      {% endif %}
    </div>
    <div class="mb-3">
      <label for="id_quality_stars" class="form-label">Estrellas de Calidad</label>
      <input type="number" name="quality_stars" value="{{ form.quality_stars.value|default:"5" }}" class="form-control" id="id_quality_stars" min="1" max="5">
      {% if form.quality_stars.errors %}
        <div class="text-danger">
          {{ form.quality_stars.errors }}
        </div>
      {% endif %}
    </div>
    <div class="mb-3">
      <label for="id_location" class="form-label">Ubicación</label>
      <select name="location" class="form-control" id="id_location">
        {% for choice in form.location.field.choices %}
            <option value="{{ choice.0 }}">{{ choice.1 }}</option>
        {% endfor %}
      </select>
      {% if form.location.errors %}
        <div class="text-danger">
          {{ form.location.errors }}
        </div>
      {% endif %}
    </div>

    <button type="submit" class="btn btn-primary">Enviar Reseña</button>
  </form>

  <div class="mt-4">
    <a href="{% url 'catalog:product_detail' product.id %}" class="btn btn-secondary">Volver al producto</a>
  </div>
</div>
{% endblock %}