shifa_products/cart/urls.py
from django.urls import path

from . import views

app_name = 'cart'

urlpatterns = [
    path(
        '',
        views.CartDetailView.as_view(),
        name='cart'
    ),
    path(
        'add_to_cart/<int:product_id>/',
        views.AddToCartCreateView.as_view(),
        name='add_to_cart'
    ),
    path(
        'item/<int:cart_item_id>/',
        views.CartItemUpdateView.as_view(),
        name='update_cart_item'
    ),
    path(
        'item/<int:cart_item_id>/delete',
        views.CartItemDeleteView.as_view(),
        name='delete_cart_item'
    ),
]

shifa_products/catalog/urls.py
from django.urls import include, path

from . import views

app_name = 'catalog'

product_urls = [
    path(
        '<int:product_id>/',
        views.ProductDetailView.as_view(),
        name='product_detail'
    ),
    path(
        '<int:product_id>/review/',
        views.ReviewCreateView.as_view(),
        name='review_form'
    ),
    path(
        '<int:product_id>/review/<int:review_id>',
        views.ReviewUpdateView.as_view(),
        name='review_update'
    ),
    path(
        '<int:product_id>/delete_review/<int:review_id>',
        views.ReviewDeleteView.as_view(),
        name='review_delete'
    )
]

category_urls = [
    path(
        '',
        views.CategoryListView.as_view(),
        name='category_list'
    ),
    path(
        '<slug:category_slug>/',
        views.ProductListView.as_view(),
        name='category_product_list'
    )
]

urlpatterns = [
    path(
        'category/', include(category_urls)
    ),
    path(
        'product/', include(product_urls)
    ),
    path(
        'search/',
        views.ProductSearchView.as_view(),
        name='product_search'
    ),
]

shifa_products/pages/urls.py
from django.urls import path
from django.views.generic import TemplateView


app_name = 'pages'

urlpatterns = [
    path(
        '',
        TemplateView.as_view(template_name='pages/index.html'),
        name='index'
    ),
    path(
        'about_us',
        TemplateView.as_view(template_name='pages/contact.html'),
        name='about_us'
    ),
    path(
        'documentation',
        TemplateView.as_view(template_name='pages/documentation.html'),
        name='documentation'
    ),
]

shifa_products/shifa_products/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path, reverse_lazy
from django.views.generic import CreateView

from .telegram_notifications import tawkto_webhook
from users.forms import UserForm

auth_urls = [
    path('', include('django.contrib.auth.urls')),
    path(
        'registration/',
        CreateView.as_view(
            template_name='registration/signup.html',
            form_class=UserForm,
            success_url=reverse_lazy('pages:index'),
        ),
        name='registration'
    )
]

urlpatterns = [
    path('', include('pages.urls', namespace='pages')),
    path('accounts/', include('allauth.urls')),
    path('admin/', admin.site.urls),
    path('auth/', include(auth_urls)),
    path('catalog/', include('catalog.urls', namespace='catalog')),
    path('users/', include('users.urls', namespace='users')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('order/', include('orders.urls', namespace='orders')),
    path('webhook/tawkto/', tawkto_webhook, name='tawkto_webhook'),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += static(
        settings.STATIC_URL, document_root=settings.STATIC_ROOT
    )
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )
    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)

shifa_products/users/urls.py
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path(
        'profile/<slug:username>',
        views.ProfileDetailView.as_view(),
        name='profile'
    ),
    path(
        'profile/<slug:username>/update/',
        views.ProfileUpdateView.as_view(),
        name='profile_update'
    ),
    path(
        'profile/create_address/',
        views.AddressUserCreateView.as_view(),
        name='address_create'
    ),
    path(
        'profile/delete_address/<int:address_id>/',
        views.AddressUserDeleteView.as_view(),
        name='address_delete'
    ),

]

shifa_products/templates/includes/footer.html
<footer class="bg-dark text-white py-4">
  <div class="container text-center">
    <p>&copy; 2024 SHIFA PRODUCTS. Todos los derechos reservados.</p>
    <p>
      <a href="#" class="text-white">Política de Privacidad</a> | 
      <a href="#" class="text-white">Términos de Servicio</a> |
      <a href="{% url 'pages:documentation' %}" class="text-white">Documentación del Código</a>
    </p>
  </div>
</footer>

shifa_products/templates/includes/header.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container">
    <a class="navbar-brand" href="{% url 'pages:index' %}">
      <i class="bi bi-capsule"></i> SHIFA PRODUCTS
    </a>
    <a class="contact-button nav-link contact-link" href="{% url 'pages:about_us' %}">
      Contacto <i class="bi bi-chat-dots"></i>
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav ms-auto">
        <li class="nav-item">
          <a class="nav-link active" href="{% url 'pages:index' %}">Inicio</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'catalog:category_list' %}">Productos</a>
        </li>
        {% if user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'users:profile' user.username %}">Perfil</a>
          </li>
          <li class="nav-item">
            <a class="btn btn-success custom-button cart-color" href="{% url 'cart:cart' %}">
              <div class="sign">
                <i class="bi bi-basket"></i>
              </div>
              <div class="text-button d-none d-sm-block">Carrito</div>
            </a>
          </li>
          <li class="nav-item">
            <form method="post" action="{% url 'logout' %}" style="display:inline;">
              {% csrf_token %}
                <button type="submit" class="custom-button logout-color">
                  <div class="sign">
                    <i class="bi bi-box-arrow-right"></i>
                  </div>  
                  <div class="text-button d-none d-sm-block">Cerrar sesión</div>
                </button>
            </form>
          </li>
        {% else %}
          <li class="nav-item">
            <a class="btn btn-primary custom-button login-color" href="{% url 'login' %}">
              <div class="sign">
                <i class="bi bi-box-arrow-in-right"></i>
              </div>
              <div class="text-button d-none d-sm-block">Iniciar sesión</div>
            </a>
          </li>
        {% endif %}
        </li>
      </ul>
    </div>
  </div>
</nav>